# Generated by Django 4.2.13 on 2024-07-07 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callboard_app', '0004_rename_user_of_the_comment_comment_author_of_the_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
